# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghealth < Formula
  desc "Unofficial Google-Health-CLI for the Google Health API"
  homepage "https://github.com/rudrankriyam/Google-Health-CLI"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.1.0/Google-Health-CLI-1.1.0-darwin-amd64.tar.gz"
      sha256 "0a401069669d487ec08eac7685cc411419cb7e80ba674b7aaf8868e96a280513"

      define_method(:install) do
        bin.install "ghealth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.1.0/Google-Health-CLI-1.1.0-darwin-arm64.tar.gz"
      sha256 "6853a20afb42ae57f28dc4b819672fde70a57b4fb0e4d515e93333820cd31982"

      define_method(:install) do
        bin.install "ghealth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.1.0/Google-Health-CLI-1.1.0-linux-amd64.tar.gz"
      sha256 "cf7a2a84bb148c724b646019e0770034470ef3e7fbd4e4c2b0b16b5b18d16ede"
      define_method(:install) do
        bin.install "ghealth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.1.0/Google-Health-CLI-1.1.0-linux-arm64.tar.gz"
      sha256 "24979445862ad291b739356c811ec79840c2a2d5b06afe027f25884ea6b9cef7"
      define_method(:install) do
        bin.install "ghealth"
      end
    end
  end

  test do
    system "#{bin}/ghealth", "version"
  end
end
