# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghealth < Formula
  desc "Unofficial Google-Health-CLI for the Google Health API"
  homepage "https://github.com/rudrankriyam/Google-Health-CLI"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.0.1/Google-Health-CLI-1.0.1-darwin-amd64.tar.gz"
      sha256 "79e4b43ac2597bfa5aa37792fe777a19e340e3ede801ceb55d274eb83756e7fc"

      define_method(:install) do
        bin.install "ghealth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.0.1/Google-Health-CLI-1.0.1-darwin-arm64.tar.gz"
      sha256 "6258c540b5cdbcfbbdbf95e7bfb22ecc369010bce418e054bee4b812e8fee29b"

      define_method(:install) do
        bin.install "ghealth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.0.1/Google-Health-CLI-1.0.1-linux-amd64.tar.gz"
      sha256 "ca985a36e164649ca0f0e191165efcc73734f9d967b1441e57733b01353fe6b5"
      define_method(:install) do
        bin.install "ghealth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rudrankriyam/Google-Health-CLI/releases/download/1.0.1/Google-Health-CLI-1.0.1-linux-arm64.tar.gz"
      sha256 "c80faac1f8357bf2d84350914df1fd1b8ff5ea1e8e877f5a076f47e8d0acfa85"
      define_method(:install) do
        bin.install "ghealth"
      end
    end
  end

  test do
    system "#{bin}/ghealth", "version"
  end
end
